# SPDX-License-Identifier: MIT
# UnFlock Authors: see AUTHORS.txt

extend = [
  { path = "./cgs-templates/templates/Makefile.template@2.toml" }
]

[env]
DOCKER_ENV_IMAGE_VERSION = "1.59.1"
HTML_PACKAGE_ASSETS = '''
  assets/fonts/FiraSans-Bold.ttf
  assets/sprites/*.png
'''
